/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yamit
 */
public class VentanaDivisas extends javax.swing.JFrame {

    /**
       - Convertir de la moneda de tu país a Dólar
       - Convertir de la moneda de tu país  a Euros
       - Convertir de la moneda de tu país  a Libras Esterlinas
       - Convertir de la moneda de tu país  a Yen Japonés
       - Convertir de la moneda de tu país  a Won sur-coreano
     */
    private String divisa1 = "";
    private String divisa2 = "";
    private String cantidad = "";
    private double dinero;
    private double cambio;
    private boolean punto = true;
    
    public VentanaDivisas() {
        initComponents();
        setSize(300,450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblSigno1 = new javax.swing.JLabel();
        lblSigno2 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        cmbDivisas1 = new javax.swing.JComboBox<>();
        cmbDivisas2 = new javax.swing.JComboBox<>();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuDivisas = new javax.swing.JMenuItem();
        jMenuMedidas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Divisas");
        setBounds(new java.awt.Rectangle(0, 0, 300, 400));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(300, 400));
        setSize(new java.awt.Dimension(300, 400));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblSigno1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblSigno1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSigno1.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 15);
        jPanel1.add(lblSigno1, gridBagConstraints);

        lblSigno2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblSigno2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSigno2.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(lblSigno2, gridBagConstraints);

        lblValor1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblValor1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        jPanel1.add(lblValor1, gridBagConstraints);

        lblValor2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblValor2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(lblValor2, gridBagConstraints);

        cmbDivisas1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbDivisas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la divisa de origen", "Peso Colombiano", "Dolar Estadounidense", "Euro", "Libra Esterlina", "Yen Japonés", "Won Surcoreano" }));
        cmbDivisas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDivisas1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cmbDivisas1, gridBagConstraints);

        cmbDivisas2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbDivisas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la divisa de destino", "Peso Colombiano", "Dolar Estadounidense", "Euro", "Libra Esterlina", "Yen Japonés", "Won Surcoreano" }));
        cmbDivisas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDivisas2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cmbDivisas2, gridBagConstraints);

        btn1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn1, gridBagConstraints);

        btn2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn2, gridBagConstraints);

        btn3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn3, gridBagConstraints);

        btn4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btn4, gridBagConstraints);

        btn5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn5, gridBagConstraints);

        btn6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn6, gridBagConstraints);

        btn7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn7, gridBagConstraints);

        btn8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn8, gridBagConstraints);

        btn9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn9, gridBagConstraints);

        btn0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn0, gridBagConstraints);

        btnPunto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnPunto, gridBagConstraints);

        btnClear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(btnClear, gridBagConstraints);

        btnBorrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(btnBorrar, gridBagConstraints);

        jMenu.setText("Menu");
        jMenu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/divisas.png"))); // NOI18N
        jMenuDivisas.setText("Conversor de Divisas");
        jMenuDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDivisasActionPerformed(evt);
            }
        });
        jMenu.add(jMenuDivisas);

        jMenuMedidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/medidas.png"))); // NOI18N
        jMenuMedidas.setText("Conversor de Medidas ");
        jMenuMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMedidasActionPerformed(evt);
            }
        });
        jMenu.add(jMenuMedidas);
        jMenu.add(jSeparator1);

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu.add(jMenuSalir);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDivisasActionPerformed
         
    }//GEN-LAST:event_jMenuDivisasActionPerformed

    private void jMenuMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMedidasActionPerformed
        VentanaMedidas medidas = new VentanaMedidas();
        medidas.setVisible(true);
        
        dispose();//para que muestre una sola ventana(cuando se abre una, se cierra la otra)
    
    }//GEN-LAST:event_jMenuMedidasActionPerformed

    private void cmbDivisas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDivisas1ActionPerformed
        divisa1 = (String) cmbDivisas1.getSelectedItem();
        
        if (divisa1.equals("Peso Colombiano")||divisa1.equals("Dolar Estadounidense") ){
            lblSigno1.setText("$");
        }else if(divisa1.equals("Libra Esterlina")){
            lblSigno1.setText("£");
        }else if(divisa1.equals("Euro")){
            lblSigno1.setText("€");
        }else if(divisa1.equals("Yen Japonés")){
            lblSigno1.setText("¥");
        }else if(divisa1.equals("Won Surcoreano")){
            lblSigno1.setText("₩");
        }
        obtenerDinero();
    }//GEN-LAST:event_cmbDivisas1ActionPerformed

    private void cmbDivisas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDivisas2ActionPerformed
        divisa2 = (String) cmbDivisas2.getSelectedItem();
        
        if (divisa2.equals("Peso Colombiano")||divisa2.equals("Dolar Estadounidense") ){
            lblSigno2.setText("$");
        }else if(divisa2.equals("Libra Esterlina")){
            lblSigno2.setText("£");
        }else if(divisa2.equals("Euro")){
            lblSigno2.setText("€");
        }else if(divisa2.equals("Yen Japonés")){
            lblSigno2.setText("¥");
        }else if(divisa2.equals("Won Surcoreano")){
            lblSigno2.setText("₩");
        }
        obtenerDinero();
    }//GEN-LAST:event_cmbDivisas2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(lblValor1.getText()== "0"){
            cantidad= "1";
        }else{
            cantidad += "1";
        }
        
        lblValor1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(lblValor1.getText()== "0"){
            cantidad= "2";
        }else{
            cantidad += "2";
        }
        lblValor1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if(lblValor1.getText()== "0"){
            cantidad= "3";
        }else{
            cantidad += "3";
        }
        lblValor1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if(lblValor1.getText()== "0"){
            cantidad= "4";
        }else{
            cantidad += "4";
        }
        lblValor1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if(lblValor1.getText()== "0"){
            cantidad= "5";
        }else{
            cantidad += "5";
        }
        lblValor1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if(lblValor1.getText()== "0"){
            cantidad= "6";
        }else{
            cantidad += "6";
        }
        lblValor1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if(lblValor1.getText()== "0"){
            cantidad= "7";
        }else{
            cantidad += "7";
        }
        lblValor1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if(lblValor1.getText()== "0"){
            cantidad= "8";
        }else{
            cantidad += "8";
        }
        lblValor1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if(lblValor1.getText()== "0"){
            cantidad= "9";
        }else{
            cantidad += "9";
        }
        lblValor1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if(cantidad != ""){
            if(lblValor1.getText()== "0"){
            cantidad= "0";
        }else{
            cantidad += "0";
        }
            lblValor1.setText(cantidad);
            obtenerDinero();
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if (punto == true){
            if(cantidad == ""){
                cantidad = "0.";
            }else{
                cantidad += ".";
            }
            lblValor1.setText(cantidad);
            
            punto = false;
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cantidad = "";
        punto = true;
        lblValor1.setText("0");
        lblValor2.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int tamaño = cantidad.length();
        if (tamaño > 0){
            punto = true;
            if (tamaño == 1){
                cantidad = "0";
            }else{
                cantidad = cantidad.substring(0,cantidad.length()-1);
            }
            lblValor1.setText(cantidad);
            obtenerDinero();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed
    
    private void obtenerDinero(){
        cantidad = lblValor1.getText();
        dinero= Double.parseDouble(cantidad);
        cambioDivisas();
        dinero = dinero * cambio;
        lblValor2.setText(String.format("%.2f", dinero));//"%.2f" => para que muestres solo 2 decimales
    }
    
    private void cambioDivisas(){
        if (divisa1.equals("Selecciona la divisa de origen")||divisa2.equals("Selecciona la divisa de destino")){
            cambio = 0;
        }else if (divisa1.equals(divisa2)){
            cambio = 1;
        }else if(divisa1.equals("Dolar Estadounidense")&& divisa2.equals("Peso Colombiano")){
            cambio = 4496.28;
        }else if(divisa1.equals("Dolar Estadounidense")&& divisa2.equals("Libra Esterlina")){
            cambio = 0.81;
        }else if(divisa1.equals("Dolar Estadounidense")&& divisa2.equals("Euro")){
            cambio = 0.91;
        }else if(divisa1.equals("Dolar Estadounidense")&& divisa2.equals("Yen Japonés")){
            cambio = 133.67;
        }else if(divisa1.equals("Dolar Estadounidense")&& divisa2.equals("Won Surcoreano")){
            cambio = 1341.34;
        }else if(divisa1.equals("Peso Colombiano")&& divisa2.equals("Dolar Estadounidense")){
            cambio = 0.00022;
        }else if(divisa1.equals("Peso Colombiano")&& divisa2.equals("Libra Esterlina")){
            cambio = 0.00018;
        }else if(divisa1.equals("Peso Colombiano")&& divisa2.equals("Euro")){
            cambio = 0.00020;
        }else if(divisa1.equals("Peso Colombiano")&& divisa2.equals("Yen Japonés")){
            cambio = 0.030;
        }else if(divisa1.equals("Peso Colombiano")&& divisa2.equals("Won Surcoreano")){
            cambio = 0.30;
        }else if(divisa1.equals("Euro")&& divisa2.equals("Peso Colombiano")){
            cambio = 4934.06;
        }else if(divisa1.equals("Euro")&& divisa2.equals("Dolar Estadounidense")){
            cambio = 1.10;
        }else if(divisa1.equals("Euro")&& divisa2.equals("Libra Esterlina")){
            cambio = 0.88;
        }else if(divisa1.equals("Euro")&& divisa2.equals("Yen Japonés")){
            cambio = 146.62;
        }else if(divisa1.equals("Euro")&& divisa2.equals("Won Surcoreano")){
            cambio = 1470.64;
        }else if(divisa1.equals("Libra Esterlina")&& divisa2.equals("Dolar Estadounidense")){
            cambio = 1.24;
        }else if(divisa1.equals("Libra Esterlina")&& divisa2.equals("Peso Colombiano")){
            cambio = 5581.64;
        }else if(divisa1.equals("Libra Esterlina")&& divisa2.equals("Euro")){
            cambio = 1.13;
        }else if(divisa1.equals("Libra Esterlina")&& divisa2.equals("Yen Japonés")){
            cambio = 165.87;
        }else if(divisa1.equals("Libra Esterlina")&& divisa2.equals("Won Surcoreano")){
            cambio = 1663.15;
        }else if(divisa1.equals("Yen Japonés")&& divisa2.equals("Dolar Estadounidense")){
            cambio = 0.0075;
        }else if(divisa1.equals("Yen Japonés")&& divisa2.equals("Libra Esterlina")){
            cambio = 0.0060;
        }else if(divisa1.equals("Yen Japonés")&& divisa2.equals("Euro")){
            cambio = 0.0068;
        }else if(divisa1.equals("Yen Japonés")&& divisa2.equals("Won Surcoreano")){
            cambio = 10.03;
        }else if(divisa1.equals("Yen Japonés")&& divisa2.equals("Peso Colombiano")){
            cambio = 33.66;
        }else if(divisa1.equals("Won Surcoreano")&& divisa2.equals("Dolar Estadounidense")){
            cambio = 0.00075;
        }else if(divisa1.equals("Won Surcoreano")&& divisa2.equals("Libra Esterlina")){
            cambio = 0.0000060;
        }else if(divisa1.equals("Won Surcoreano")&& divisa2.equals("Yen Japonés")){
            cambio = 0.100;
        }else if(divisa1.equals("Won Surcoreano")&& divisa2.equals("Euro")){
            cambio = 0.00068;
        }else if(divisa1.equals("Won Surcoreano")&& divisa2.equals("Peso Colombiano")){
            cambio = 3.36;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDivisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPunto;
    private javax.swing.JComboBox<String> cmbDivisas1;
    private javax.swing.JComboBox<String> cmbDivisas2;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDivisas;
    private javax.swing.JMenuItem jMenuMedidas;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblSigno1;
    private javax.swing.JLabel lblSigno2;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    // End of variables declaration//GEN-END:variables
}
