/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yamit
 */
public class VentanaMedidas extends javax.swing.JFrame {

    private String medida1 = "";
    private String medida2 = "";
    private String longitud = "";
    private double medida, cambio;
    private boolean punto = true;
    
    public VentanaMedidas() {
        initComponents();
        setSize(300,450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblSigno1 = new javax.swing.JLabel();
        lblSigno2 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        cmbMedidas1 = new javax.swing.JComboBox<>();
        cmbMedidas2 = new javax.swing.JComboBox<>();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuDivisas = new javax.swing.JMenuItem();
        jMenuMedidas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor Medidas de Longitud");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblSigno1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblSigno1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSigno1.setText("Km");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 15);
        jPanel1.add(lblSigno1, gridBagConstraints);

        lblSigno2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblSigno2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSigno2.setText("Km");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(lblSigno2, gridBagConstraints);

        lblValor1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblValor1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        jPanel1.add(lblValor1, gridBagConstraints);

        lblValor2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblValor2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(lblValor2, gridBagConstraints);

        cmbMedidas1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbMedidas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la unidad de medida", "Kilometro", "Metro", "Centimetro", "Milimetro", "Milla", "Yarda", "Pie", "Pulgada" }));
        cmbMedidas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedidas1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cmbMedidas1, gridBagConstraints);

        cmbMedidas2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbMedidas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona la unidad de medida ", "Kilometro", "Metro", "Centimetro", "Milimetro", "Milla", "Yarda", "Pie", "Pulgada" }));
        cmbMedidas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedidas2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cmbMedidas2, gridBagConstraints);

        btn1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn1, gridBagConstraints);

        btn2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn2, gridBagConstraints);

        btn3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn3, gridBagConstraints);

        btn4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btn4, gridBagConstraints);

        btn5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn5, gridBagConstraints);

        btn6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn6, gridBagConstraints);

        btn7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn7, gridBagConstraints);

        btn8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn8, gridBagConstraints);

        btn9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn9, gridBagConstraints);

        btn0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btn0, gridBagConstraints);

        btnPunto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnPunto, gridBagConstraints);

        btnClear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(btnClear, gridBagConstraints);

        btnBorrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(btnBorrar, gridBagConstraints);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu.setText("Menu");
        jMenu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });

        jMenuDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/divisas.png"))); // NOI18N
        jMenuDivisas.setText("Conversor de Divisas");
        jMenuDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDivisasActionPerformed(evt);
            }
        });
        jMenu.add(jMenuDivisas);

        jMenuMedidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/medidas.png"))); // NOI18N
        jMenuMedidas.setText("Conversor de Medidas");
        jMenu.add(jMenuMedidas);
        jMenu.add(jSeparator1);

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu.add(jMenuSalir);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
         
    }//GEN-LAST:event_jMenuActionPerformed

    private void jMenuDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDivisasActionPerformed
        VentanaDivisas divisas = new VentanaDivisas();
        divisas.setVisible(true);
        
        dispose();//para que muestre una sola ventana(cuando se abre una, se cierra la otra)
    
    }//GEN-LAST:event_jMenuDivisasActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void cmbMedidas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedidas1ActionPerformed
        medida1 = (String) cmbMedidas1.getSelectedItem();
        
        if (medida1.equals("Kilometro")){
            lblSigno1.setText("Km");
        }else if(medida1.equals("Metro")){
            lblSigno1.setText("m");
        }else if(medida1.equals("Centimetro")){
            lblSigno1.setText("cm");
        }else if(medida1.equals("Milimetro")){
            lblSigno1.setText("mm");
        }else if(medida1.equals("Milla")){
            lblSigno1.setText("mi");
        }else if(medida1.equals("Yarda")){
            lblSigno1.setText("yd");
        }else if(medida1.equals("Pie")){
            lblSigno1.setText("ft");
        }else if(medida1.equals("Pulgada")){
            lblSigno1.setText("in");
        }
        obtenerMedida();
    }//GEN-LAST:event_cmbMedidas1ActionPerformed

    private void cmbMedidas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedidas2ActionPerformed
        medida2 = (String) cmbMedidas2.getSelectedItem();
        
        if (medida2.equals("Kilometro")){
            lblSigno2.setText("Km");
        }else if(medida2.equals("Metro")){
            lblSigno2.setText("m");
        }else if(medida2.equals("Centimetro")){
            lblSigno2.setText("cm");
        }else if(medida2.equals("Milimetro")){
            lblSigno2.setText("mm");
        }else if(medida2.equals("Milla")){
            lblSigno2.setText("mi");
        }else if(medida2.equals("Yarda")){
            lblSigno2.setText("yd");
        }else if(medida2.equals("Pie")){
            lblSigno2.setText("ft");
        }else if(medida2.equals("Pulgada")){
            lblSigno2.setText("in");
        }
        obtenerMedida();
    }//GEN-LAST:event_cmbMedidas2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(lblValor1.getText()== "0"){
            longitud= "1";
        }else{
            longitud += "1";
        }
        
        lblValor1.setText(longitud);
        obtenerMedida();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(lblValor1.getText()== "0"){
            longitud= "2";
        }else{
            longitud += "2";
        }
        
        lblValor1.setText(longitud);
        obtenerMedida();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if(lblValor1.getText()== "0"){
            longitud= "3";
        }else{
            longitud += "3";
        }
        
        lblValor1.setText(longitud);
        obtenerMedida();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if(lblValor1.getText()== "0"){
            longitud= "4";
        }else{
            longitud += "4";
        }
        
        lblValor1.setText(longitud);
        obtenerMedida();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if(lblValor1.getText()== "0"){
            longitud= "5";
        }else{
            longitud += "5";
        }
        
        lblValor1.setText(longitud);
        obtenerMedida();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if(lblValor1.getText()== "0"){
            longitud= "6";
        }else{
            longitud += "6";
        }
        
        lblValor1.setText(longitud);
        obtenerMedida();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if(lblValor1.getText()== "0"){
            longitud= "7";
        }else{
            longitud += "7";
        }
        
        lblValor1.setText(longitud);
        obtenerMedida();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if(lblValor1.getText()== "0"){
            longitud= "8";
        }else{
            longitud += "8";
        }
        
        lblValor1.setText(longitud);
        obtenerMedida();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if(lblValor1.getText()== "0"){
            longitud= "9";
        }else{
            longitud += "9";
        }
        
        lblValor1.setText(longitud);
        obtenerMedida();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if(longitud != ""){
            if(lblValor1.getText()== "0"){
            longitud= "0";
        }else{
            longitud += "0";
        }
            lblValor1.setText(longitud);
            obtenerMedida();
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if (punto == true){
            if(longitud == ""){
                longitud = "0.";
            }else{
                longitud += ".";
            }
            lblValor1.setText(longitud);
            
            punto = false;
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        longitud = "";
        punto = true;
        lblValor1.setText("0");
        lblValor2.setText("0");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int tamaño = longitud.length();
        if (tamaño > 0){
            punto = true;
            if (tamaño == 1){
                longitud = "0";
            }else{
                longitud = longitud.substring(0,longitud.length()-1);
            }
            lblValor1.setText(longitud);
            obtenerMedida();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void obtenerMedida(){
        longitud = lblValor1.getText();
        medida= Double.parseDouble(longitud);
        cambioMedidas();
        medida = medida * cambio;
        lblValor2.setText(String.format("%.2f", medida));//"%.3f" => para que muestres solo 2 decimales
    }
    
    private void cambioMedidas(){
        if (medida1.equals("Selecciona la unidad de medida")||medida2.equals("Selecciona la unidad de medida")){
            cambio = 0;
        }else if (medida1.equals(medida2)){
            cambio = 1;
        }else if(medida1.equals("Kilometro")&& medida2.equals("Metro")){
            cambio = 1000;
        }else if(medida1.equals("Kilometro")&& medida2.equals("Centimetro")){
            cambio = 100000;
        }else if(medida1.equals("Kilometro")&& medida2.equals("Milimetro")){
            cambio = 1000000;
        }else if(medida1.equals("Kilometro")&& medida2.equals("Milla")){
            cambio = 0.621371;
        }else if(medida1.equals("Kilometro")&& medida2.equals("Yarda")){
            cambio = 1093.61;
        }else if(medida1.equals("Kilometro")&& medida2.equals("Pie")){
            cambio = 3280.84;
        }else if(medida1.equals("Kilometro")&& medida2.equals("Pulgada")){
            cambio = 39370.1;
        }else if(medida1.equals("Metro")&& medida2.equals("Kilometro")){
            cambio = 0.001;
        }else if(medida1.equals("Metro")&& medida2.equals("Centimetro")){
            cambio = 100;
        }else if(medida1.equals("Metro")&& medida2.equals("Milimetro")){
            cambio = 1000;
        }else if(medida1.equals("Metro")&& medida2.equals("Milla")){
            cambio = 0.000621371;
        }else if(medida1.equals("Metro")&& medida2.equals("Yarda")){
            cambio = 1.09361;
        }else if(medida1.equals("Metro")&& medida2.equals("Pie")){
            cambio = 3.28084;
        }else if(medida1.equals("Metro")&& medida2.equals("Pulgada")){
            cambio = 39.3701;
        }else if(medida1.equals("Centimetro")&& medida2.equals("Kilometro")){
            cambio = 0.00001;
        }else if(medida1.equals("Centimetro")&& medida2.equals("Metro")){
            cambio = 0.01;
        }else if(medida1.equals("Centimetro")&& medida2.equals("Milimetro")){
            cambio = 10;
        }else if(medida1.equals("Centimetro")&& medida2.equals("Milla")){
            cambio = 0.0000062137;
        }else if(medida1.equals("Centimetro")&& medida2.equals("Yarda")){
            cambio = 0.0109361;
        }else if(medida1.equals("Centimetro")&& medida2.equals("Pie")){
            cambio = 0.0328084;
        }else if(medida1.equals("Centimetro")&& medida2.equals("Pulgada")){
            cambio = 0.393701;
        }else if(medida1.equals("Milimetro")&& medida2.equals("Kilometro")){
            cambio = 0.000001;
        }else if(medida1.equals("Milimetro")&& medida2.equals("Metro")){
            cambio = 0.001;
        }else if(medida1.equals("Milimetro")&& medida2.equals("Centimetro")){
            cambio = 0.1;
        }else if(medida1.equals("Milimetro")&& medida2.equals("Milla")){
            cambio = 6.214e-7;
        }else if(medida1.equals("Milimetro")&& medida2.equals("Yarda")){
            cambio = 0.00109361;
        }else if(medida1.equals("Milimetro")&& medida2.equals("Pie")){
            cambio = 0.00328084 ;
        }else if(medida1.equals("Milimetro")&& medida2.equals("Pulgada")){
            cambio = 0.0393701;
        }else if(medida1.equals("Milla")&& medida2.equals("Kilometro")){
            cambio = 1.60934;
        }else if(medida1.equals("Milla")&& medida2.equals("Metro")){
            cambio = 1609.34;
        }else if(medida1.equals("Milla")&& medida2.equals("Centimetro")){
            cambio = 160934;
        }else if(medida1.equals("Milla")&& medida2.equals("Milimetro")){
            cambio = 1609000;
        }else if(medida1.equals("Milla")&& medida2.equals("Yarda")){
            cambio = 1760;
        }else if(medida1.equals("Milla")&& medida2.equals("Pie")){
            cambio = 5280 ;
        }else if(medida1.equals("Milla")&& medida2.equals("Pulgada")){
            cambio = 63360;
        }else if(medida1.equals("Yarda")&& medida2.equals("Kilometro")){
            cambio = 0.0009144;
        }else if(medida1.equals("Yarda")&& medida2.equals("Metro")){
            cambio =  0.9144;
        }else if(medida1.equals("Yarda")&& medida2.equals("Centimetro")){
            cambio =  91.44;
        }else if(medida1.equals("Yarda")&& medida2.equals("Milimetro")){
            cambio = 914.4;
        }else if(medida1.equals("Yarda")&& medida2.equals("Milla")){
            cambio = 0.000568182;
        }else if(medida1.equals("Yarda")&& medida2.equals("Pie")){
            cambio = 3 ;
        }else if(medida1.equals("Yarda")&& medida2.equals("Pulgada")){
            cambio = 36;
        }else if(medida1.equals("Pie")&& medida2.equals("Kilometro")){
            cambio = 0.0003048;
        }else if(medida1.equals("Pie")&& medida2.equals("Metro")){
            cambio =  0.3048;
        }else if(medida1.equals("Pie")&& medida2.equals("Centimetro")){
            cambio =  30.48;
        }else if(medida1.equals("Pie")&& medida2.equals("Milimetro")){
            cambio = 304.8;
        }else if(medida1.equals("Pie")&& medida2.equals("Milla")){
            cambio = 0.000189394;
        }else if(medida1.equals("Pie")&& medida2.equals("Yarda")){
            cambio = 0.333333  ;
        }else if(medida1.equals("Pie")&& medida2.equals("Pulgada")){
            cambio = 12;
        }else if(medida1.equals("Pulgada")&& medida2.equals("Kilometro")){
            cambio = 0.0000254;
        }else if(medida1.equals("Pulgada")&& medida2.equals("Metro")){
            cambio =   0.0254;
        }else if(medida1.equals("Pulgada")&& medida2.equals("Centimetro")){
            cambio =  2.54 ;
        }else if(medida1.equals("Pulgada")&& medida2.equals("Milimetro")){
            cambio = 25.4 ;
        }else if(medida1.equals("Pulgada")&& medida2.equals("Milla")){
            cambio = 0.000015783;
        }else if(medida1.equals("Pulgada")&& medida2.equals("Yarda")){
            cambio = 0.0277778;
        }else if(medida1.equals("Pulgada")&& medida2.equals("Pie")){
            cambio = 0.8333333;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMedidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPunto;
    private javax.swing.JComboBox<String> cmbMedidas1;
    private javax.swing.JComboBox<String> cmbMedidas2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDivisas;
    private javax.swing.JMenuItem jMenuMedidas;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblSigno1;
    private javax.swing.JLabel lblSigno2;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    // End of variables declaration//GEN-END:variables
}
